version: '3'

services:

#database
  mysqldb:
    image: mysql
    # env_file:
    #   - .env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    #   - MYSQL_DATABASE=$DB_NAME
    # command: [console.log(MYSQL_DATABASE);]
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - docker-compose-backend

#frontend
  trainee_frontend:
    depends_on:
      - trainee_backend
    build:
      context: ./trainee_frontend
      environment:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
        - 80:80  
    networks:
      - docker-compose-frontend
    volumes:
      - ./trainee_frontend/nginx:/etc/nginx/conf.d

#backend
  trainee_backend:
    depends_on:
      - mysqldb
    build: ./trainee_backend
 
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    ports:
      - 8080:8080
    networks:
      - docker-compose-backend
      - docker-compose-frontend

    # mem_limit: 400M
    # cpus: 0.5 
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 400M
            reservations:
              cpus: 0.25
              memory: 128M


networks:
  docker-compose-frontend:
  docker-compose-backend:


  


